name: Feature Branch

on:
  push:
    branches-ignore:
      - 'master'
      - 'develop'

jobs:
  test:
    name: Build and run unit tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JVM
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.10
          java-package: jdk
          architecture: x64

      - name: Caching maven dependencies
        uses: actions/cache@v1
        env:
          cache-name: cache-maven-dependencies
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}

      - name: Maven generate sources
        run: mvn generate-sources

      - name: Push Admin API to documentation
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_PACKAGE_RELEASE_TOKEN }}
        with:
          source-directory: 'target/generated-sources/markdown'
          destination-github-username: ${{ secrets.GH_PACKAGE_RELEASE_USER }}
          destination-repository-username: 'CaritasDeutschland'
          destination-repository-name: 'documentation'
          user-email: github@beratung.caritas.de
          target-branch: 'adminapi'
          commit_message: 'docs: updated user service admin api description'

      - name: Maven Package
        run: mvn -B -Pprod clean package -Dskip.unit-tests=true -Dskip.integration-tests=true

      - name: Maven Verify
        run: mvn -B -Pprod clean verify